### ISSUE TITLE
Moonbeam WalletConnect  click `connect` button show `Webpage not available`

### ISSUE THREAD

**Issue by iceqing** [nova-wallet/nova-wallet-android-releases#1]
How to reproduce errors？

NovaWallet -> Dapps -> moonbeam -> WalletConnect -> OK button -> Connect button

![image](https://user-images.githubusercontent.com/39587710/161515175-cf8969bd-48dd-4f21-9218-08692c83ddff.png)

**Comment by valentunn** [comment]
Hey @iceqing ! Wallet Connect support is not available via Nova DApp browser. However, soon we will start integrating Metamask support for EVM-based chains
